// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGG6yG2HbBGYQX0RyPaNQizkmVhJg0DEU',
    appId: '1:863104395978:web:260f0a621d3e47f73ae233',
    messagingSenderId: '863104395978',
    projectId: 'phone-number-c13c6',
    authDomain: 'phone-number-c13c6.firebaseapp.com',
    storageBucket: 'phone-number-c13c6.appspot.com',
    measurementId: 'G-ETJD4M6GEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkR2VqvQVrX3czZtnDRDTOmt74dnZRgvE',
    appId: '1:863104395978:android:a183696f02d2442f3ae233',
    messagingSenderId: '863104395978',
    projectId: 'phone-number-c13c6',
    storageBucket: 'phone-number-c13c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI9h0lVgTGh6bEIvV9FaEAOFIgL3Ru7uc',
    appId: '1:863104395978:ios:0897c2c7c7fd1bef3ae233',
    messagingSenderId: '863104395978',
    projectId: 'phone-number-c13c6',
    storageBucket: 'phone-number-c13c6.appspot.com',
    iosBundleId: 'com.example.careercraft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI9h0lVgTGh6bEIvV9FaEAOFIgL3Ru7uc',
    appId: '1:863104395978:ios:0897c2c7c7fd1bef3ae233',
    messagingSenderId: '863104395978',
    projectId: 'phone-number-c13c6',
    storageBucket: 'phone-number-c13c6.appspot.com',
    iosBundleId: 'com.example.careercraft',
  );
}
